services:
  blazorcrud_proyecto01:
    build:
      context: ./BlazorCrud_Proyecto01
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BlazorDB;User=sa;Password=Roger1974.;TrustServerCertificate=true;MultipleActiveResultSets=true

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ContenedorLibros.Db
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Roger1974.
